from event_indexing.categories import CATEGORY_CRIME, CATEGORY_MEDICAL, CATEGORY_HAZARD, CATEGORY_POWER_OUTAGE

'''
Every source should have a category map, map one category for test purposes. Follow same naming convention.
'''

BRADFORD_SO_INCIDENT_CATEGORY_MAP = {
    'TRAFFIC CRASH': CATEGORY_CRIME,
}

CLARK_COUNTY_INCIDENT_CATEGORY_MAP = {
    'Medical Aid - C Level': CATEGORY_MEDICAL,
}

LAFAYETTE_911_INCIDENT_CATEGORY_MAP = {
    'Incoming Call': CATEGORY_CRIME,
}

OAKLAND_PD_INCIDENT_CATEGORY_MAP = {
    'LOUD MUSIC': CATEGORY_CRIME,
}

FAYETTEVILLE_911_INCIDENT_CATEGORY_MAP = {
    'THEFT': CATEGORY_CRIME,
}

SEATTLE_PD_INCIDENT_CATEGORY_MAP = {
    'HAZARDS': CATEGORY_HAZARD,
}

PARIS_TEXAS_911_INCIDENT_CATEGORY_MAP = {
    'Transfer': CATEGORY_MEDICAL,
}

ESCAMBIA_COUNTY_SO_INCIDENT_CATEGORY_MAP = {
    'SUSP VEH': CATEGORY_CRIME,
}

ORANGE_COUNTY_SO_INCIDENT_CATEGORY_MAP = {
    'BATTERY': CATEGORY_CRIME,
}

PGE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

SCE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Upgrading Equipment': CATEGORY_POWER_OUTAGE,
}

OAEP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

APP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

SDGE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

AU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Under Investigation': CATEGORY_POWER_OUTAGE,
}

ACE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Wires Down': CATEGORY_POWER_OUTAGE,
}

SMUD_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

SRP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

PSE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

XE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

FLORIDA_HWP_INCIDENT_CATEGORY_MAP = {
    'OBSTRUCTION ON HIGHWAY': CATEGORY_HAZARD,
}

IPL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

NG_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

CPSE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

REC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE
}

LGEKU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE
}

NOVEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

IREA_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

FPL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

NES_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

CMP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

IP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

NIPSCO_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

PNM_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

MAE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

TAEP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

JEMC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

HEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Motor Vehicle Accident': CATEGORY_POWER_OUTAGE,
}

GEMC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

BEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

NNEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

BB_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

NL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

SU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP = {
    'Power Outage': CATEGORY_POWER_OUTAGE,
}

INCIDENT_CATEGORY_MAP = {
    'BradfordSOCad': BRADFORD_SO_INCIDENT_CATEGORY_MAP,
    'ClarkCountyFDCad': CLARK_COUNTY_INCIDENT_CATEGORY_MAP,
    'OaklandPDCad': OAKLAND_PD_INCIDENT_CATEGORY_MAP,
    'Lafayette911Cad': LAFAYETTE_911_INCIDENT_CATEGORY_MAP,
    'Fayetteville911Cad': FAYETTEVILLE_911_INCIDENT_CATEGORY_MAP,
    'SeattlePDCad': SEATTLE_PD_INCIDENT_CATEGORY_MAP,
    'ParisTexas911Cad': PARIS_TEXAS_911_INCIDENT_CATEGORY_MAP,
    'EscambiaCountySOCad': ESCAMBIA_COUNTY_SO_INCIDENT_CATEGORY_MAP,
    'OrangeCountySOCad': ORANGE_COUNTY_SO_INCIDENT_CATEGORY_MAP,
    'PGEPowerOutages': PGE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'PSEPowerOutages': PSE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'OEAPPowerOutages': OAEP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'SCEPowerOutages': SCE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'APPowerOutages': APP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'SDGEPowerOutages': SDGE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'AUPowerOutages': AU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'ACEPowerOutages': ACE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'SMUDPowerOutages': SMUD_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'SRPPowerOutages': SRP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'XEPowerOutages': XE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'FloridaHWPCad': FLORIDA_HWP_INCIDENT_CATEGORY_MAP,
    'IPLPowerOutages': IPL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NGPowerOutages': NG_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'CPSEPowerOutages': CPSE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'RECPowerOutages': REC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'LGEKUPowerOutages': LGEKU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'IREAPowerOutages': IREA_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NOVECPowerOutages': NOVEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'FPLPowerOutages': FPL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'CMPPowerOutages': CMP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'IPPowerOutages': IP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NESPowerOutages': NES_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NIPSCOPowerOutages': NIPSCO_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'PNMPowerOutages': PNM_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'MAEPowerOutages': MAE_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'TAEPPowerOutages': TAEP_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'JEMCPowerOutages': JEMC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'HECPowerOutages': HEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'GEMCPowerOutages': GEMC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'BECPowerOutages': BEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NNECPowerOutages': NNEC_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'BBPowerOutages': BB_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'NLPowerOutages': NL_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
    'SUPowerOutages': SU_POWER_OUTAGES_INCIDENT_CATEGORY_MAP,
}
